scripts: Reformat with shfmt
Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -20,62 +20,66 @@
 set -u
 
 # avoid [[ which is not POSIX sh.
-if test "$#" != 1 ; then
-  echo "$0 requires an argument."
-  exit 1
+if test "$#" != 1; then
+	echo "$0 requires an argument."
+	exit 1
 fi
 
-if test ! -f "$1" ; then
-  echo "file does not exist: $1"
-  exit 1
+if test ! -f "$1"; then
+	echo "file does not exist: $1"
+	exit 1
 fi
 
 # Do not create a change id if requested
-if test "false" = "$(git config --bool --get gerrit.createChangeId)" ; then
-  exit 0
+if test "false" = "$(git config --bool --get gerrit.createChangeId)"; then
+	exit 0
 fi
 
 if git rev-parse --verify HEAD >/dev/null 2>&1; then
-  refhash="$(git rev-parse HEAD)"
+	refhash="$(git rev-parse HEAD)"
 else
-  refhash="$(git hash-object -t tree /dev/null)"
+	refhash="$(git hash-object -t tree /dev/null)"
 fi
 
-random=$({ git var GIT_COMMITTER_IDENT ; echo "$refhash" ; cat "$1"; } | git hash-object --stdin)
+random=$({
+	git var GIT_COMMITTER_IDENT
+	echo "$refhash"
+	cat "$1"
+} | git hash-object --stdin)
 dest="$1.tmp.${random}"
 
 trap 'rm -f "${dest}"' EXIT
 
-if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
-   echo "cannot strip comments from $1"
-   exit 1
+if ! git stripspace --strip-comments <"$1" >"${dest}"; then
+	echo "cannot strip comments from $1"
+	exit 1
 fi
 
-if test ! -s "${dest}" ; then
-  echo "file is empty: $1"
-  exit 1
+if test ! -s "${dest}"; then
+	echo "file is empty: $1"
+	exit 1
 fi
 
 reviewurl="$(git config --get gerrit.reviewUrl)"
-if test -n "${reviewurl}" ; then
-  if ! git interpret-trailers --parse < "$1" | grep -q '^Link:.*/id/I[0-9a-f]\{40\}$' ; then
-    if ! git interpret-trailers \
-          --trailer "Link: ${reviewurl%/}/id/I${random}" < "$1" > "${dest}" ; then
-      echo "cannot insert link footer in $1"
-      exit 1
-    fi
-  fi
+if test -n "${reviewurl}"; then
+	if ! git interpret-trailers --parse <"$1" | grep -q '^Link:.*/id/I[0-9a-f]\{40\}$'; then
+		if ! git interpret-trailers \
+			--trailer "Link: ${reviewurl%/}/id/I${random}" <"$1" >"${dest}"; then
+			echo "cannot insert link footer in $1"
+			exit 1
+		fi
+	fi
 else
-  # Avoid the --in-place option which only appeared in Git 2.8
-  # Avoid the --if-exists option which only appeared in Git 2.15
-  if ! git -c trailer.ifexists=doNothing interpret-trailers \
-        --trailer "Change-Id: I${random}" < "$1" > "${dest}" ; then
-    echo "cannot insert change-id line in $1"
-    exit 1
-  fi
+	# Avoid the --in-place option which only appeared in Git 2.8
+	# Avoid the --if-exists option which only appeared in Git 2.15
+	if ! git -c trailer.ifexists=doNothing interpret-trailers \
+		--trailer "Change-Id: I${random}" <"$1" >"${dest}"; then
+		echo "cannot insert change-id line in $1"
+		exit 1
+	fi
 fi
 
-if ! mv "${dest}" "$1" ; then
-  echo "cannot mv ${dest} to $1"
-  exit 1
+if ! mv "${dest}" "$1"; then
+	echo "cannot mv ${dest} to $1"
+	exit 1
 fi
